### ISSUE TITLE
How can I change these icons especially?

### ISSUE THREAD

**Issue by c4lliope** [alvatip/Nordzy-cursors#4]
I'm mixed up inside your code's hierarchy, so I could use help opening the shapes for the icons in this cursor line:
![nordzy_line](https://user-images.githubusercontent.com/30454698/200415122-4355363c-9b93-42ff-95da-18db71a6e16c.png)

**Comment by alvatip** [comment]
The easiest way to do so is to:

1. Clone the repository
2. Go into `tools/svgs/nordzy-templates` and open `Nordzy-cursors.svg` or `Nordzy-cursors-white.svg` depending on the one you want to modify.
3. Make your modifications (you might have to 'ungroup' all the cursors => ctrl + g on inkscape)
4. Run `linux.sh` script and wait for it to complete (will tell "The cursors theme is finished!")
5. It should have created the theme in `archives`

If needed, I can extract all the cursors in separated/individual `.svg` file
I can also post here the specific names of the cursors if you wish to.

Hopes it helps, feel free to ask more questions if encountering any troubles

**Comment by juniorhdezp** [comment]
Hello. 
When I install the cursor theme on mac via mousecape only one color from the options palette is installed. How can i fix this? Thanks for your time.
![Captura de Pantalla 2022-11-25 a la(s) 2 27 07 p  m](https://user-images.githubusercontent.com/119073897/204039999-e088e42a-93cb-498f-b72b-696bbec93b38.png)

**Comment by alvatip** [comment]
@juniorhdezp 
I haven't done the mousecape file for the white version yet, I will try to find some time in the following days to make it

**Comment by alvatip** [comment]
@juniorhdezp 
I made the .cape file for the white version :)
You can find it in the MacOs folder.

**Comment by juniorhdezp** [comment]
Thank you very much! This cursor is the best I've seen on the web for Mousecape. Congratulations!
