### ISSUE TITLE
1.0.0 - no nordzy_cursors_windows.zip

### ISSUE THREAD

**Issue by guyg-codes** [alvatip/Nordzy-cursors#7]
Hi @alvatip, really appreciate the work, lovely Nord theming :D

One small issue - there appears to be no nordzy_cursors_windows.zip file within the 1.0.0 release.  I've grabbed 0.6.0 for now as I don't plan to use the Catpuccin flavour.

No rush, just thought others may miss the availablity in earlier releases.

Cheers,
Guy

**Comment by alvatip** [comment]
Hi @guyg-codes,

I just rendered them and uploaded them in the last commit + release :wink: 

Cheers
